@echo off
echo Vérification de l'environnement virtuel...
if not exist venv (
    echo Création de l'environnement virtuel...
    python -m venv venv
)

echo Activation de l'environnement virtuel...
call venv\Scripts\activate

echo Installation des dépendances...
pip install -r requirements.txt

echo Démarrage de l'application...
python index.py
